### ISSUE TITLE
Add counter-ion swaps for maintaining charge neutrality

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/protons#104]
Greg has added functionality to saltswap that should allow us to plug saltswappers into our Simulation style classes. This should allow the code to maintain charge neutrality.

- [ ] I should design a `CounterIonProtonDrive` that can interact with a salinator/swapper from `saltswap` code. 
- [ ] We should extend functionality of `ConstantPHSimulation` and `ConstantPHCalibration` as needed to facilitate the new class. 
- [ ] Add a salt reporter?  

As John points out below, in the future we will also want to support compatibility with a full osmostat simulation.

**Comment by jchodera** [comment]
We have distinct functionalities we want to add:
* (1) the ability to swap a single water/ion to maintain charge neutrality during a protonation state change---we need this for the paper
* (2) the ability to alternate with salt insertion/deletion using the osmostat---we want to punt on this to a later paper

**Comment by bas-rustenburg** [comment]
Yes, thanks for pointing that out. This should cover only the maintaining of charge neutrality for now.

**Comment by bas-rustenburg** [comment]
Updated.

**Comment by bas-rustenburg** [comment]
Implemented this feature in #113.
