### ISSUE TITLE
Split off stable Amber-based API

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/protons#58]
Based on discussion in #57 .

The simplest, most flexible thing I can think of is to change the main `ProtonDrive` class to a base class without an `__init__` function, and then have an Amber based init function for an `AmberProtonDrive` or `CpinProtonDrive`.

When we change the format around, we can implement a new constructor for an `XmlProtonDrive`, or something similar. I think that should work.

**Comment by jchodera** [comment]
This sounds great. We could use `AmberProtonDrive` and `ForceFieldProtonDrive` or something.

**Comment by bas-rustenburg** [comment]
This has been accomplished.
